/*
  Warnings:

  - You are about to drop the `admin` table. If the table is not empty, all the data it contains will be lost.

*/
-- DropForeignKey
ALTER TABLE "admin" DROP CONSTRAINT "admin_id_fkey";

-- DropTable
DROP TABLE "admin";

-- CreateTable
CREATE TABLE "role" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "role" STRING NOT NULL,
    "levelId" STRING NOT NULL,

    CONSTRAINT "role_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "level" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "levelName" STRING NOT NULL,
    "features" STRING[],

    CONSTRAINT "level_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "role" ADD CONSTRAINT "role_id_fkey" FOREIGN KEY ("id") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "level" ADD CONSTRAINT "level_id_fkey" FOREIGN KEY ("id") REFERENCES "role"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
