-- CreateEnum
CREATE TYPE "Roletype" AS ENUM ('ADMIN', 'HR', 'EMPLOYEE', 'GUEST');

-- CreateTable
CREATE TABLE "user" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" STRING NOT NULL,
    "email" STRING NOT NULL,
    "verified" BOOL NOT NULL DEFAULT false,
    "password" STRING NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "user_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "role" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "role" "Roletype" NOT NULL DEFAULT 'GUEST',
    "levelId" STRING NOT NULL,

    CONSTRAINT "role_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "level" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "levelName" STRING NOT NULL,
    "features" STRING[],

    CONSTRAINT "level_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "user_email_key" ON "user"("email");

-- AddForeignKey
ALTER TABLE "role" ADD CONSTRAINT "role_id_fkey" FOREIGN KEY ("id") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "level" ADD CONSTRAINT "level_id_fkey" FOREIGN KEY ("id") REFERENCES "role"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
